### ISSUE TITLE
Offline ordering file

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fsttable#13]
The `fstproxy` object contains the following information:

* _filter_: a binary vector (C++) with a mask that is set to each selected row. This mask is relatively small: a 1 billion records table will have a 125 MB mask (8 bits per byte and each row is 1 bit)
* _slice map_: an `unsigned int` or `unsigned long long` vector (depends on the size of the result) with the positions in the result vector of each selected element in the mask. This vector can be large: a 1 billion row selection will have a _slice map_ of 4 GB (unsigned int). A 5 billion row selection will have _slice map_ of 40 GB (unsigned long long). So these maps are potentially too large for the user's memory.
* _column selection_: the selected columns in the `fsttable`
* _virtual columns_: for constructed columns that have single element operators these are expressions that define the new column (no actual data stored).

A _slice map_ that is too large for memory can be stored on-disk in a single column `fst` file with the ordering. When needed, the file can be read per chunk, not requiring extra memory.

If we decide to implement this, the _index map_ file could be saved in a temporary directory or perhaps alongside the original `fst` file (that might not be possible due to access restrictions).

**Comment by MarcusKlik** [comment]
If we decide to implement a `fststore` (or equivalent), see #14, the ordering file can be kept alongside the original `fst` file.

**Comment by martinblostein** [comment]
Perhaps this issue be split into implementing each of *filter*, *slice map*, *column selection* and *virtual columns*, and then off-line storage of a large slice map?

**Comment by MarcusKlik** [comment]
Yes, thanks, good idea!

**Comment by MarcusKlik** [comment]
Now splitted into #24, #25 and #26, thanks @martinblostein!
